import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import NFTCard from "../components/NFTCard";
import SearchBar from "../components/SearchBar";

export default function Home() {
  return (
    <div className="h-full bg-primary ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-full border-black w-10/12 mx-auto flex gap-8 py-6">
        {/* first column */}
        <div className="h-full border-black w-10/12">
          {/* header */}
          <header>
            <SearchBar />
            <Banner />
          </header>
          {/* main content -> articles */}
          <main className="h-full w-full overflow-y-auto p-4 flex gap-4">
            <NFTCard imageUrl="/nft1.jpeg" />
            <NFTCard imageUrl="/nft2.png" />
            <NFTCard imageUrl="/nft3.jpeg" />
            <NFTCard imageUrl="/nft4.jpg" />
          </main>
        </div>
        {/* second column */}
        <div className="h-full  w-2/12 border-black bg-primaryLight rounded-2xl"></div>
      </div>
    </div>
  );
}
