import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="h-full bg-[#131129]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-full border-2 w-10/12 mx-auto">

      </div>
    </div>
  );
}
